In [1]:
import numpy as np
import pandas as pd
import requests
import urllib
import urllib.request
import urllib.parse
from socket import socket
from bs4 import BeautifulSoup

In [2]:
import urllib.parse, urllib.request

In [3]:
url = r"http://houseinfo.co.kr/sub.html"
params = r"?menu=9&i_mode=search&i_zipetc=&i_bub_cd1=X&i_bub_cd2=&region_code1=&region_code2=&region_code3=&i_selday1=2018-04-21&i_selday2=2018-07-21&i_money_value1=&i_money_value2=&auction_result=0&i_sort=0&i_sort2=0&i_tuksu=&i_yu_cnt1=0&i_yu_cnt2=999&i_area_value1=&i_area_value2=&p_usagecode01%5B%5D=01"
url = url + params

In [6]:
df = pd.read_html(url, encoding="euc-kr")
# df = pd.read_html(url, encoding="utf-8")

In [29]:
df

[                                                   0   1   2   3
 0  전체  2018  2017  2016  2015  2014  2013  2012  ...  타경 NaN  검색,
        0                                                  1      2  \
 0   간편검색  예) 소재지 (시도,구군,읍면동) * 건물명칭 * 이해관계인 (채무자, 채권자, 소유자)    NaN
 1   관할법원  전체  서울  부산  인천  의정부  수원  춘천  청주  대전  대구  창원  전...  소 재 지
 2   매각기일                                                  ~    금 액
 3   경매결과  전체  진행물건  종결물건  매각/잔금납부/배당종결  신건  유찰  매각  변경  ...   정렬방식
 4  유 찰 수  최소  0 1 2 3 4 5 6 7 8 9 10  ~  최대  1  2  3  4 ...    면 적

                                                    3
 0                                                NaN
 1  전체  서울  경기  인천  부산  대구  대전  광주  울산  경북  경남  충북...
 2  감정가  최저가  -최소금액-  1십만원  5백만원  1천만원  2천만원  3천만원...
 3  선택1  용도별  지역별  사건번호↑  사건번호↓  감정가↑  감정가↓  최저가↑ ...
 4                                    건물면적 대지면적 ㎡ ~ ㎡  ,
        0      1      2                                                  3
 0    주거용    NaN    주거용  아파트  주택  다세대(빌라)  다가구(원룸등)  근린주택  오피스텔(주거)  도시...
 1    NaN    주거용    NaN                                                NaN
 2    상업용    NaN    상업용  근린시설  근린상가  상가  상가(점포)  공장  아파트형공장  숙박시설  주유소 ...
 3    NaN    상업용    NaN                                                NaN
 4     토지    NaN     토지  대지  임야  전  답  과수원  잡종지  공장용지  도로  구거  유지  목장용지...
 5    NaN     토지    NaN                                                NaN
 6  기타부동산    NaN  기타부동산  축사  콘도  학교  주차장  묘지  광업권  어업권  농가관련시설  종교시설  기...
 7    NaN  기타부동산    NaN                                                NaN
 8   차량선박    NaN   차량선박      승용자동차  승합자동차  화물자동차  중장비  덤프트럭  선박  SUV  차량기타
 9    NaN   차량선박    NaN                                                NaN,
     0    1
 0 NaN  주거용,
     0    1
 0 NaN  상업용,
     0   1
 0 NaN  토지,
     0      1
 0 NaN  기타부동산,
     0     1
 0 NaN  차량선박,
      0    1                  2  \
 0  NaN   사진               사건번호
 1  NaN  NaN    2017-9245(1)아파트
 2  NaN  NaN   2017-12066(1)아파트
 3  NaN  NaN    2017-6185(1)아파트
 4  NaN  NaN    2017-7614(1)아파트
 5  NaN  NaN    2016-6112(1)아파트
 6  NaN  NaN   2017-62059(1)아파트
 7  NaN  NaN    2017-1622(1)아파트
 8  NaN  NaN    2017-5082(1)아파트
 9  NaN  NaN   2017-12035(1)아파트
 10 NaN  NaN   2017-11539(1)아파트
 11 NaN  NaN  2017-105194(1)아파트
 12 NaN  NaN   2017-22577(1)아파트
 13 NaN  NaN  2017-511541(1)아파트
 14 NaN  NaN   2017-13567(1)아파트
 15 NaN  NaN   2017-27368(1)아파트
 16 NaN  NaN   2017-80215(1)아파트
 17 NaN  NaN    2017-2337(1)아파트
 18 NaN  NaN    2017-6820(1)아파트
 19 NaN  NaN    2017-9249(1)아파트
 20 NaN  NaN    2017-9652(1)아파트

                                                     3                  4  \
 0                                              소재지/특징         (입찰기간)매각기일
 1   [서울특별시 서초구 방배동 755-14 리첸시아 방배 제3층 제303호]  감정가:...  2018-06-26  (80%)
 2   [대전광역시 서구 관저동 1398 느리울마을 제1207동 제20층 제2002호]  ...  2018-06-04  (70%)
 3   [전라남도 목포시 상동 1003-2 거성센트럴파크주상복합아파트 제1동 제4층 제40...  2018-06-04  (56%)
 4   [전라남도 목포시 옥암동 1338 목포옥암골드클래스아파트 제105동 제8층 제801...  2018-06-04  (70%)
 5   [서울특별시 송파구 풍성로24길 42, 310동 2층 205호 (풍납동,현대리버빌아...  2018-06-04  (64%)
 6   [경기도 김포시 장기동 2071-2 초당마을래미안한강 제607동 제7층 제702호]...  2018-05-29  (70%)
 7   [대전광역시 유성구 반석동 622 반석마을5단지아파트 제505동 제5층 제502호]...  2018-05-29  (70%)
 8   [대전광역시 서구 월평동 302 황실타운 제108동 제14층 제1406호]  감정가...  2018-05-29  (70%)
 9   [대전광역시 중구 태평동 407 삼부아파트 제22동 제10층 제107호]  감정가:...  2018-05-29  (70%)
 10  [울산광역시 남구 옥동 182 옥동현대아파트 제102동 제9층 제903호]  감정가...  2018-05-29  (80%)
 11  [서울특별시 영등포구 여의도동 55-1 대우트럼프월드 제24층 제에이2402호]  ...  2018-05-29  (80%)
 12  [인천광역시 부평구 부평동 149-10외 1필지 금강아파트 제4층 제503호]  감...  2018-05-29  (70%)
 13  [인천광역시 부평구 부개동 104-5 신삼호아파트 제비동 제3층 제303호]  감정...  2018-05-29  (70%)
 14  [경기도 동두천시 동두천동 524-2 우방아이유쉘아파트 제304동 제2층 제202호...  2018-05-29  (70%)
 15  [경기도 남양주시 호평동 678 호평마을 한라비발디아파트 제1801동 제9층 제90...  2018-05-29  (70%)
 16  [경기도 남양주시 진접읍 장현리 621 풍양마을길훈아파트 제104동 제2층 제202...  2018-05-29  (70%)
 17  [충청북도 영동군 영동읍 부용리 417 지평더웰아파트 제101동 제2층 제201호]...  2018-05-29  (80%)
 18  [충청남도 서산시 지곡면 화천리 523-11외 3필지 지곡미래아파트 제101동 제4...  2018-05-29  (49%)
 19  [충청남도 당진시 신평면 금천리 1642 당진신평엘아이지리가아파트 제102동 제11...  2018-05-29  (70%)
 20  [충청남도 당진시 송악읍 복운리 1629-3 신성미소지움1단지아파트 제104동 제1...  2018-05-29  (70%)

           5
 0        결과
 1    취하(1회)
 2   재진행(1회)
 3    유찰(2회)
 4    유찰(1회)
 5    유찰(2회)
 6   재진행(1회)
 7   재진행(1회)
 8   재진행(1회)
 9   재진행(1회)
 10  재매각(1회)
 11   유찰(1회)
 12   유찰(1회)
 13   유찰(1회)
 14   유찰(1회)
 15   유찰(1회)
 16   유찰(1회)
 17   유찰(1회)
 18   유찰(2회)
 19   유찰(1회)
 20   유찰(1회)  ]

In [19]:
df[8]

,0,1,2,3,4,5
0,NaN,사진,사건번호,소재지/특징,(입찰기간)매각기일,결과
1,NaN,NaN,2017-9245(1)아파트,[서울특별시 서초구 방배동 755-14 리첸시아 방배 제3층 제303호] 감정가:...,2018-06-26 (80%),취하(1회)
2,NaN,NaN,2017-12066(1)아파트,[대전광역시 서구 관저동 1398 느리울마을 제1207동 제20층 제2002호] ...,2018-06-04 (70%),재진행(1회)
3,NaN,NaN,2017-6185(1)아파트,[전라남도 목포시 상동 1003-2 거성센트럴파크주상복합아파트 제1동 제4층 제40...,2018-06-04 (56%),유찰(2회)
4,NaN,NaN,2017-7614(1)아파트,[전라남도 목포시 옥암동 1338 목포옥암골드클래스아파트 제105동 제8층 제801...,2018-06-04 (70%),유찰(1회)
5,NaN,NaN,2016-6112(1)아파트,"[서울특별시 송파구 풍성로24길 42, 310동 2층 205호 (풍납동,현대리버빌아...",2018-06-04 (64%),유찰(2회)
6,NaN,NaN,2017-62059(1)아파트,[경기도 김포시 장기동 2071-2 초당마을래미안한강 제607동 제7층 제702호]...,2018-05-29 (70%),재진행(1회)
7,NaN,NaN,2017-1622(1)아파트,[대전광역시 유성구 반석동 622 반석마을5단지아파트 제505동 제5층 제502호]...,2018-05-29 (70%),재진행(1회)
8,NaN,NaN,2017-5082(1)아파트,[대전광역시 서구 월평동 302 황실타운 제108동 제14층 제1406호] 감정가...,2018-05-29 (70%),재진행(1회)
9,NaN,NaN,2017-12035(1)아파트,[대전광역시 중구 태평동 407 삼부아파트 제22동 제10층 제107호] 감정가:...,2018-05-29 (70%),재진행(1회)
10,NaN,NaN,2017-11539(1)아파트,[울산광역시 남구 옥동 182 옥동현대아파트 제102동 제9층 제903호] 감정가...,2018-05-29 (80%),재매각(1회)
11,NaN,NaN,2017-105194(1)아파트,[서울특별시 영등포구 여의도동 55-1 대우트럼프월드 제24층 제에이2402호] ...,2018-05-29 (80%),유찰(1회)
12,NaN,NaN,2017-22577(1)아파트,[인천광역시 부평구 부평동 149-10외 1필지 금강아파트 제4층 제503호] 감...,2018-05-29 (70%),유찰(1회)
13,NaN,NaN,2017-511541(1)아파트,[인천광역시 부평구 부개동 104-5 신삼호아파트 제비동 제3층 제303호] 감정...,2018-05-29 (70%),유찰(1회)
14,NaN,NaN,2017-13567(1)아파트,[경기도 동두천시 동두천동 524-2 우방아이유쉘아파트 제304동 제2층 제202호...,2018-05-29 (70%),유찰(1회)
15,NaN,NaN,2017-27368(1)아파트,[경기도 남양주시 호평동 678 호평마을 한라비발디아파트 제1801동 제9층 제90...,2018-05-29 (70%),유찰(1회)
16,NaN,NaN,2017-80215(1)아파트,[경기도 남양주시 진접읍 장현리 621 풍양마을길훈아파트 제104동 제2층 제202...,2018-05-29 (70%),유찰(1회)
17,NaN,NaN,2017-2337(1)아파트,[충청북도 영동군 영동읍 부용리 417 지평더웰아파트 제101동 제2층 제201호]...,2018-05-29 (80%),유찰(1회)
18,NaN,NaN,2017-6820(1)아파트,[충청남도 서산시 지곡면 화천리 523-11외 3필지 지곡미래아파트 제101동 제4...,2018-05-29 (49%),유찰(2회)
19,NaN,NaN,2017-9249(1)아파트,[충청남도 당진시 신평면 금천리 1642 당진신평엘아이지리가아파트 제102동 제11...,2018-05-29 (70%),유찰(1회)
20,NaN,NaN,2017-9652(1)아파트,[충청남도 당진시 송악읍 복운리 1629-3 신성미소지움1단지아파트 제104동 제1...,2018-05-29 (70%),유찰(1회)